"""
Django settings for campify project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

environment = os.environ.get("ENVIRONMENT")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if os.environ.get("ENVIRONMENT") == "production":
    ALLOWED_HOSTS = ["20.197.18.109","campusfest.live","www.campusfest.live","localhost",]
    DJANGO_CSRF_TRUSTED_ORIGINS = ["http://20.197.18.109","http://campusfest.live","https://campusfest.live","http://www.campusfest.live","https://www.campusfest.live",]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'payment.apps.PaymentConfig',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",

]


ROOT_URLCONF = 'campify.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'campify.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR,"media")


SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

ACCOUNT_SIGNUP_REDIRECT_URL = "profile_register"
LOGIN_REDIRECT_URL = 'profile_register'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
if not RAZORPAY_KEY_ID:
    raise Exception("Missing razorpay_key_id environment variable")

RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")
if not RAZORPAY_KEY_SECRET:
    raise Exception("Missing razorpay_key_secret environment variable")



CASHFREE_CLIENT_ID = os.getenv("CASHFREE_CLIENT_ID")
if not CASHFREE_CLIENT_ID:
    raise Exception("Missing CASHFREE_CLIENT_ID environment variable")

CASHFREE_CLIENT_SECRET = os.getenv("CASHFREE_CLIENT_SECRET")
if not CASHFREE_CLIENT_SECRET:
    raise Exception("Missing CASHFREE_CLIENT_SECRET environment variable")

RAZOR_PAY_CALLBACK_URL = "payment_verify"

# storage

# Toggle whether to use DigitalOcean Spaces (S3) storage backend.
# Useful for enabling Spaces in development: set USE_SPACES=1 in your .env
USE_SPACES = os.environ.get('USE_SPACES', '').lower() in ('1', 'true', 'yes')

# Use DigitalOcean Spaces if ENVIRONMENT==production or USE_SPACES is enabled
if os.environ.get('ENVIRONMENT') == 'production' or USE_SPACES:
    # ========= DigitalOcean Spaces Storage ========= #
    # Configure storages using the Django 5.x `STORAGES` setting so the
    # StorageHandler can create the correct backend.
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    # Prefix inside the bucket where media files will be stored. You can
    # override it with AWS_S3_LOCATION in .env, otherwise default to
    # the project folder name so objects go under that prefix in the Space.
    AWS_S3_LOCATION = "media"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": AWS_S3_LOCATION,
            },
        },
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")

    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")

    # Allow overriding endpoint from env (useful for local testing or explicit endpoints)
    AWS_S3_ENDPOINT_URL = os.environ.get(
        "AWS_S3_ENDPOINT_URL") or f"https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
    AWS_S3_CUSTOM_DOMAIN = os.environ.get(
        "AWS_S3_CUSTOM_DOMAIN") or f"{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com"

    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False

    # For django-storages >=1.13: you can choose to set ACL headers or
    # configure a bucket policy that grants public read access. By default
    # we avoid sending ACL headers (safer when bucket policy controls access).
    # If you want uploaded objects to be publicly readable via Spaces,
    # set SPACES_PUBLIC=1 in your .env — this will set the ACL to public-read.
    SPACES_PUBLIC = os.environ.get('SPACES_PUBLIC', '').lower() in ('1', 'true', 'yes')
    if SPACES_PUBLIC:
        AWS_DEFAULT_ACL = 'public-read'
        AWS_S3_OBJECT_PARAMETERS = {
            "CacheControl": "max-age=86400",
        }
    else:
        AWS_DEFAULT_ACL = None
        AWS_S3_OBJECT_PARAMETERS = {
            "CacheControl": "max-age=86400",
        }

    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    # Point MEDIA_URL to the location prefix so URLs use the folder in the Space
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    MEDIA_ROOT = ""

    try:
        from django.core.files.storage import default_storage

        # Try to instantiate the S3 storage backend now so default_storage
        # won't remain uninitialized (None) and cause AttributeError when
        # Django attempts to call storage methods from model fields.
        try:
            from storages.backends.s3boto3 import S3Boto3Storage

            storage_instance = S3Boto3Storage()
            default_storage._wrapped = storage_instance
        except Exception:
            # Fallback: reset wrapped so it'll try to initialize lazily later
            default_storage._wrapped = None
            import logging

            logging.exception("Unable to instantiate S3Boto3Storage; default_storage left unwrapped")
    except Exception:
        # ignore import errors at settings load time
        pass

else:

    # Development: use local filesystem for media so uploaded images are saved to ./media/
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    # MEDIA_URL and MEDIA_ROOT already set above with sensible defaults

# ================================================ #
