# Generated by Django 5.2.3 on 2025-06-25 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('interested_event', models.CharField(choices=[('tech', 'Tech Event'), ('non_tech', 'Non Tech Event'), ('both', 'Both')], default='both', max_length=100)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='profile_img/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
