# Generated by Django 5.2.3 on 2025-06-26 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
