# Generated by Django 5.2.3 on 2025-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_gender_profile_phone_no_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='logo_dot_sm.png', upload_to='profile_img/'),
        ),
    ]
