# Generated by Django 5.2.3 on 2025-09-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='logo_dot_sm.png', null=True, upload_to='profile_img/'),
        ),
    ]
