# Generated by Django 5.2.3 on 2025-09-06 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.UUID('1fd23cee-b72a-4c80-8c11-4ebf73745a81'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('club_name', models.CharField(max_length=255)),
                ('no_of_slots', models.IntegerField()),
                ('event_details', models.TextField()),
                ('img', models.ImageField(default='logo_dot_sm.png', upload_to='event_img/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='event_img/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='event_img/')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='event_img/')),
                ('volunteer_name', models.CharField(max_length=255)),
                ('volunteer_phone_no', models.IntegerField(max_length=10)),
                ('volunteer_position', models.CharField(max_length=255)),
                ('registion_opening_date', models.DateField()),
                ('registion_closing_date', models.DateField()),
                ('registion_on_date', models.DateField()),
                ('event_starting_time', models.TimeField()),
                ('event_type', models.CharField(choices=[('free', 'Free Event'), ('paid', 'Paid Event')])),
            ],
        ),
    ]
