# Generated by Django 5.2.3 on 2025-09-06 14:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('cdace3f5-115e-40b3-8a4c-06e897edebcd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteer_phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
