# Generated by Django 5.2.3 on 2025-09-06 14:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_event_id_alter_event_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.UUID('df268c7c-d7bd-4635-9dd5-e0919b65a373'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('free', 'Free Event'), ('paid', 'Paid Event')], null=True),
        ),
    ]
