# Generated by Django 5.2.3 on 2025-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('free', 'Free Event'), ('paid', 'Paid Event')], default='paid'),
        ),
    ]
