# Generated by Django 5.2.3 on 2025-09-07 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
