# Generated by Django 5.2.3 on 2025-09-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_slots',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
