# Generated by Django 5.2.3 on 2025-12-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_current_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=10),
        ),
    ]
