# Generated by Django 5.2.3 on 2025-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_event_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='logo_dot_sm.png', upload_to='image/event_img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/event_img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/event_img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/event_img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='logo_dot_sm.png', null=True, upload_to='image/profile_img/'),
        ),
    ]
