# Generated by Django 5.2.3 on 2026-01-31 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_event_img_alter_event_img_2_alter_event_img_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('no_of_slots', models.IntegerField()),
                ('current_slots', models.IntegerField()),
                ('event_details', models.TextField()),
                ('img', models.ImageField(default='logo_dot_sm.png', upload_to='image/event_img/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='image/event_img/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='image/event_img/')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
