# Generated by Django 5.2.3 on 2026-01-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_slots',
        ),
        migrations.RemoveField(
            model_name='game',
            name='no_of_slots',
        ),
    ]
