# Generated by Django 5.2.3 on 2026-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_game_current_slots_remove_game_no_of_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='no_checkin_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='current_slots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_of_slots',
            field=models.PositiveIntegerField(),
        ),
    ]
