# Generated by Django 5.2.3 on 2025-09-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_alter_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
    ]
