# Generated by Django 5.2.3 on 2025-12-08 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_booking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
