# Generated by Django 5.2.3 on 2025-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_booking_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
