# Generated by Django 5.2.3 on 2025-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_booking_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
