# Generated by Django 5.2.3 on 2026-01-31 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_event_created_by'),
        ('payment', '0005_booking_is_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event',
        ),
        migrations.AddField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.game'),
        ),
    ]
