# Generated by Django 5.2.3 on 2026-01-31 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_event_no_checkin_allowed_alter_event_current_slots_and_more'),
        ('payment', '0006_remove_booking_event_booking_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='game',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_checked_in',
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_checkin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
